### Input
# input rgba image path (default to None, can be load in GUI too)
input: 
# input text prompt (default to None, can be input in GUI too)
prompt:
negative_prompt: "ugly, bad anatomy, blurry, pixelated obscure, unnatural colors, poor lighting, dull, and unclear, cropped, lowres, low quality, artifacts, duplicate, morbid, mutilated, poorly drawn face, deformed, dehydrated, bad proportions"
# input mesh for stage 2 (auto-search from stage 1 output path if None)
mesh:
# estimated elevation angle for input image 
elevation: 0 # DEFAULT 0
# reference image resolution
ref_size: 256
# density thresh for mesh extraction
density_thresh: 1 # default 1
# CUSTOM CODE: Additional (partial) point cloud input
point_cloud:

### Output
outdir: logs
mesh_format: obj
save_path: ???

### Training
# use mvdream instead of sd 2.1
mvdream: True
# use imagedream
imagedream: False
# use stable-zero123 instead of zero123-xl
stable_zero123: False 
# guidance loss weights (0 to disable)
lambda_sd: 0.1 # default 1, # 0.1 after GradeADreamer
lambda_zero123: 0 # default 0
# warmup rgb supervision for image-to-3d
warmup_rgb_loss: True
# training batch size per iter
batch_size: 1 # default 1
# training iterations for stage 1
iters: 5000
# whether to linearly anneal timestep
anneal_timestep: True #default True
# training iterations for stage 2
iters_refine: 2000
# training camera radius
radius: 2.5 #default 2.5
# training camera fovy
fovy: 49.1
# training camera min elevation
min_ver: -30 # DEFAULT-30
# training camera max elevation
max_ver: 30 # DEFAULT 30
# checkpoint to load for stage 1 (should be a ply file)
load:
# whether allow geom training in stage 2
train_geo: True
# prob to invert background color during training (0 = always black, 1 = always white)
invert_bg_prob: 0.5 #DEFAULT 0.5

### GUI
gui: False
force_cuda_rast: False
# GUI resolution
H: 800
W: 800

### Gaussian splatting
num_pts: 6000
sh_degree: 0 #default 0 
position_lr_init: 0.001 #default 0.001 #CHANGED 0.00016 lucid dreamer
position_lr_final: 0.00002 #0.000005 was good so far #default 0.00002 #0.0000016 after GradeADreamer
position_lr_delay_mult: 0.01 # default 0.02 #0.01 lucid dreamer
position_lr_max_steps: 300 #default 300
feature_lr: 0.005 #default 0.01, #0.005 after GradeADreamer
feature_lr_final: 0.003 #default 0.01, #0.003 after GradeADreamer
opacity_lr: 0.05 #default 0.05
scaling_lr: 0.005 #default 0.005
scaling_lr_final: 0.005 #default 0.005
rotation_lr: 0.001 #default 0.005, #0,001 after GradeADreamer
rotation_lr_final: 0.0002 #default 0.005, #0,001 after GradeADreamer
percent_dense: 0.005 #0.003 #0.003 #default 0.01 , 0.003 after GradeADreamer
density_start_iter: 0 #default 0
density_end_iter: 1500 #default 3000
#CUSTOM default 50
densification_interval: 100 #default 50, #55 after GradeADreamer
opacity_reset_interval: 500 #default 700, #500 after GradeADreamer
opacity_reset_start_iter: 0
densify_grad_threshold: 0.00075 #default 0.01

# pcd completion
captured_camera_angles_only_until: 500

### Textured Mesh
geom_lr: 0.0001
texture_lr: 0.2