### Input
# input rgba image path (default to None, can be load in GUI too)
input: 
# input text prompt (default to None, can be input in GUI too)
prompt:
negative_prompt:
# input mesh for stage 2 (auto-search from stage 1 output path if None)
mesh:
# estimated elevation angle for input image 
elevation: 0
# reference image resolution
ref_size: 256
# density thresh for mesh extraction
density_thresh: 1
# CUSTOM CODE: Additional (partial) point cloud input
point_cloud:

### Output
outdir: logs
mesh_format: obj
save_path: ???

### Training
# use mvdream instead of sd 2.1
mvdream: False
# use imagedream
imagedream: False
# use stable-zero123 instead of zero123-xl
stable_zero123: False 
# guidance loss weights (0 to disable)
lambda_sd: 0.1
lambda_zero123: 0
# warmup rgb supervision for image-to-3d
warmup_rgb_loss: True
# training batch size per iter
batch_size: 1 # LucidDreamer # 2 after GradeADreamer
# training iterations for stage 1
iters: 5000
# whether to linearly anneal timestep
anneal_timestep: True
# training iterations for stage 2
iters_refine: 700
# training camera radius
radius: 2.5
# training camera fovy
fovy: 49.1
# training camera min elevation
min_ver: -30
# training camera max elevation
max_ver: 30
# checkpoint to load for stage 1 (should be a ply file)
load:
# whether allow geom training in stage 2
train_geo: False
# prob to invert background color during training (0 = always black, 1 = always white)
invert_bg_prob: 0.8

### GUI
gui: False
force_cuda_rast: False
# GUI resolution
H: 800
W: 800

### Gaussian splatting
num_pts: 100000
sh_degree: 0 #default 0 
# take some much smaller lr for second stage
position_lr_init: 0.00005 #0.00016 #LucidDreamer #default 0.001 #CHANGED
position_lr_final: 0.000001 #0.0000016 #default 0.00002 #0.0000016 after GradeADreamer
position_lr_delay_mult: 0.02 # default 0.02
position_lr_max_steps: 300 #default 300
feature_lr: 0.001 #0.005 #default 0.01, #0.005 after GradeADreamer
feature_lr_final: 0.0005 #0.003 #default 0.01, #0.005 after GradeADreamer
opacity_lr: 0.01 #0.05 #default 0.05
scaling_lr: 0.001 #0.005 #default 0.005
scaling_lr_final: 0.0001 #0.001 #default 0.005
rotation_lr: 0.0005 #0.001 #default 0.005, #0,001 after GradeADreamer
rotation_lr_final: 0.0001 #0.0002 #default 0.005, #0,001 after GradeADreamer
percent_dense: 0.003 # LUCID Dreamer #default 0.01
density_start_iter: 0 #default 0
density_end_iter: 3000 #default 3000
#CUSTOM default 50
densification_interval: 10000 #100 # after LucidDreamer #default 50, 
opacity_reset_interval: 10000 # don't reset in the second stage # after GradeADreamer #default 700
densify_grad_threshold: 0.00075 # Lucid Dreamer 0.00075 #default 0.01

# For testing purposes (set True for practically running the vanilla method)
only_dynamic_splats: False

### Textured Mesh
geom_lr: 0.0001
texture_lr: 0.2